// Simulated terminal code
let simulatedCode = [
    'user@cipher-viper:~$ Initializing...',
    'user@cipher-viper:~$ Boot sequence complete.',
    'user@cipher-viper:~$ Accessing server...',
    'user@cipher-viper:~$ Retrieving data...',
    'user@cipher-viper:~$ Connecting to secure database...',
    'user@cipher-viper:~$ Data acquired.',
    'user@cipher-viper:~$ Uploading results...',
    'user@cipher-viper:~$ Task complete.',
    // Add a variety of other messages (100+ examples)
    'user@cipher-viper:~$ Scanning for vulnerabilities...',
    'user@cipher-viper:~$ Encrypting data...',
    'user@cipher-viper:~$ Hack mode activated...',
    'user@cipher-viper:~$ Bypassing firewall...',
    'user@cipher-viper:~$ Triggering exploit...',
    'user@cipher-viper:~$ Sending payload...',
    'user@cipher-viper:~$ Access granted.',
    'user@cipher-viper:~$ Exploit successful.',
    'user@cipher-viper:~$ Command execution started...',
    'user@cipher-viper:~$ Unauthorized access detected...',
    'user@cipher-viper:~$ Root access achieved.',
    'user@cipher-viper:~$ Database dumped.',
    'user@cipher-viper:~$ Securing backdoor...',
    'user@cipher-viper:~$ Modifying system files...',
    'user@cipher-viper:~$ Encrypting connections...',
    'user@cipher-viper:~$ Exploit complete.',
    'user@cipher-viper:~$ Clearing logs...',
    'user@cipher-viper:~$ Deleting evidence...',
    'user@cipher-viper:~$ Patching vulnerabilities...',
    'user@cipher-viper:~$ Installing trojan...',
    'user@cipher-viper:~$ Generating encryption keys...',
    'user@cipher-viper:~$ Backdoor active.',
    'user@cipher-viper:~$ File system accessed...',
    'user@cipher-viper:~$ Admin privileges assigned...',
    'user@cipher-viper:~$ Simulating attack...',
    'user@cipher-viper:~$ Initiating shell...',
    'user@cipher-viper:~$ Target locked...',
    'user@cipher-viper:~$ Attack launched...',
    'user@cipher-viper:~$ Receiving shell...',
    'user@cipher-viper:~$ Escalating privileges...',
    'user@cipher-viper:~$ Disabling security...',
    'user@cipher-viper:~$ Activating exploit...',
    'user@cipher-viper:~$ Breaking encryption...',
    'user@cipher-viper:~$ Cracking password...',
    'user@cipher-viper:~$ Stealth mode enabled...',
    'user@cipher-viper:~$ Scanning IP range...',
    'user@cipher-viper:~$ Detecting open ports...',
    'user@cipher-viper:~$ Stealth scanning...',
    'user@cipher-viper:~$ Downloading resources...',
    'user@cipher-viper:~$ Traversing file system...',
    'user@cipher-viper:~$ Command injection detected...',
    'user@cipher-viper:~$ Brute-forcing password...',
    'user@cipher-viper:~$ Spoofing IP...',
    'user@cipher-viper:~$ Creating remote shell...',
    'user@cipher-viper:~$ Bypassing login...',
    'user@cipher-viper:~$ Decrypting files...',
    'user@cipher-viper:~$ Initiating system takeover...',
    'user@cipher-viper:~$ Checking rootkit...',
    'user@cipher-viper:~$ Checking for shell access...',
    'user@cipher-viper:~$ Rootkit installed.',
    'user@cipher-viper:~$ Compiling exploit...',
    'user@cipher-viper:~$ Uploading malware...',
    'user@cipher-viper:~$ Configuring system...',
    'user@cipher-viper:~$ Clearing system logs...',
    'user@cipher-viper:~$ Connecting to botnet...',
    'user@cipher-viper:~$ Adding remote access...',
    'user@cipher-viper:~$ Scanning files...',
    'user@cipher-viper:~$ Extracting data...',
    'user@cipher-viper:~$ Backdoor confirmed...',
    'user@cipher-viper:~$ Resetting system...',
    'user@cipher-viper:~$ Password found...',
    'user@cipher-viper:~$ Closing port...',
    'user@cipher-viper:~$ Transmitting payload...',
    'user@cipher-viper:~$ Keylogging active...',
    'user@cipher-viper:~$ Payload confirmed...',
    'user@cipher-viper:~$ Triggering exploit...',
    'user@cipher-viper:~$ Hacking complete...',
    'user@cipher-viper:~$ Disabling encryption...',
    'user@cipher-viper:~$ Collecting data...',
    'user@cipher-viper:~$ Attacking network...',
    'user@cipher-viper:~$ Initiating DDoS...',
    'user@cipher-viper:~$ Attack successful...',
    'user@cipher-viper:~$ Compromised data...',
    'user@cipher-viper:~$ Closing connections...',
    'user@cipher-viper:~$ Target system offline...',
    'user@cipher-viper:~$ System hijacked...',
    'user@cipher-viper:~$ Checking server...',
    'user@cipher-viper:~$ Scanning network...',
    'user@cipher-viper:~$ Scan complete...',
    'user@cipher-viper:~$ Exploiting vulnerability...',
    'user@cipher-viper:~$ Waiting for confirmation...',
    'user@cipher-viper:~$ Attack in progress...',
    'user@cipher-viper:~$ Data breach detected...',
    'user@cipher-viper:~$ Remotely accessing server...',
    'user@cipher-viper:~$ Encrypting network traffic...',
    'user@cipher-viper:~$ Patching system...',
    'user@cipher-viper:~$ Creating backup...',
    'user@cipher-viper:~$ Target locked...',
    'user@cipher-viper:~$ Accessing sensitive files...',
    'user@cipher-viper:~$ Triggering code injection...',
    'user@cipher-viper:~$ Loading exploit...',
    'user@cipher-viper:~$ System manipulation...',
    'user@cipher-viper:~$ Deleting files...',
    'user@cipher-viper:~$ Closing backdoor...',
    'user@cipher-viper:~$ All systems compromised...'
  ];
  
  let i = 0;
  let terminalElement = document.getElementById("simulated-code");
  
  // Generate a random code from the array
  function generateRandomCode() {
    return simulatedCode[Math.floor(Math.random() * simulatedCode.length)];
  }
  
  // Simulate the hacking process at a faster speed and with more random codes
  function simulateHacking() {
    terminalElement.textContent += '\n' + generateRandomCode();
    setTimeout(simulateHacking, 200); // Faster speed, update every 200ms
  }
  
  window.onload = simulateHacking;  // Start simulation when page loads
  